version: '3.8'
services:
  database:
    image: postgres:12.3-alpine
    container_name: musement_weather.test.postgres
    restart: on-failure
    volumes:
      - musement_weather_test_postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER:-root}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-root}
      POSTGRES_DB: ${DB_DATABASE:-MusementWeather}
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - ${DOCKER_DB_PORT:-54321}:5432
    networks:
      - musement_weather_test

  web:
    image: musement_weather/web:latest
    container_name: musement_weather.test.web
    ports:
      - ${DOCKER_WEB_PORT:-80}:80
    networks:
      - musement_weather_test

  app:
    container_name: musement_weather.test.based_app
    networks:
      - musement_weather_test

  app-test:
    image: musement_weather/app:test
    container_name: musement_weather.test.app
    user: ${CURRENT_USER:-1000:1000}
    build:
      context: ./
      dockerfile: docker/test/containers/app/Dockerfile
    environment:
      - PHP_IDE_CONFIG=serverName=_
    volumes:
      - .:/app
      - /app/vendor
    depends_on:
      - database
      - app
    networks:
      - musement_weather_test

volumes:
  musement_weather_test_postgres:

networks:
  musement_weather_test:
    name: musement_weather_test
    driver: bridge
